/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows10
 */
public class Project4 extends javax.swing.JFrame {

    /**
     * Creates new form Project5
     */
    public Project4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Drinks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ชามะนาวโซดา.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 110, 90));

        jLabel2.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel2.setText("ชามะนาวโซดา");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 40));

        jLabel4.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel4.setText("39 ฿");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำมะนาวโซดา.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\แตงโมมะนาวโซดา.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 120, 90));

        jLabel7.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel7.setText("49 ฿");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 60));

        jLabel8.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel8.setText("แตงโมมะนาว");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, 40));

        jLabel9.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel9.setText("49 ฿");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, 50));

        jLabel10.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel10.setText("บลูเบอร์รี่");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, 80));

        jLabel12.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel12.setText("39 ฿");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, 80));

        jLabel13.setFont(new java.awt.Font("TH Kodchasal", 1, 21)); // NOI18N
        jLabel13.setText("มะนาวมิ้นโซดา");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\สละปั่น.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 140, 80));

        jLabel15.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel15.setText("20 ฿");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, -1, 40));

        jLabel16.setFont(new java.awt.Font("TH Kodchasal", 1, 22)); // NOI18N
        jLabel16.setText("น้ำเลม่อน");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, 80));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำเลมอน.jpg")); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 140));

        jLabel18.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel18.setText("น้ำใบเตย");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, 30));

        jLabel19.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel19.setText("39 ฿");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 306, -1, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำสตอ.jpg")); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 130, 80));

        jLabel21.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel21.setText("49 ฿");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, 40));

        jLabel22.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel22.setText("น้ำราสเบอร์รี่");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, 80));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ราสเบอรรี่.jpg")); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, 90));

        jLabel24.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel24.setText("น้ำเชอร์รี่");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, 30));

        jLabel25.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel25.setText("59 ฿");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำใบเตย.jpg")); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, 80));

        jLabel27.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel27.setText("น้ำสละ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, -1, 40));

        jLabel28.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel28.setText("39 ฿");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, 40));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำสัปปะรด.jpg")); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 130, 80));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำแตงโม.jpg")); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 120, 90));

        jLabel11.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel11.setText("แตงโมป่ัน");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, 80));

        jLabel29.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel29.setText("39 ฿");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 156, -1, 80));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำบลู.jpg")); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, 90));

        jLabel33.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel33.setText("นำ้สตอเบอร์รี่");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 80));

        jLabel34.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel34.setText("39 ฿");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 306, -1, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\น้ำเชอร์รี่.jpg")); // NOI18N
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 110, 80));

        jLabel36.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel36.setText("น้ำสัปปะรด");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 40));

        jLabel37.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel37.setText("49 ฿");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, 40));

        jButton1.setFont(new java.awt.Font("TH Baijam", 1, 14)); // NOI18N
        jButton1.setText("กลับ");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 70, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ทะเล.jpg")); // NOI18N
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Project3 pj3 = new Project3();
        dispose();
        pj3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
