/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Windows10
 */
public class Project5 extends javax.swing.JFrame {

    /**
     * Creates new form Project5
     */
    public Project5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel38 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\photo-1578474846511-04ba529f0b88.jfif.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Snacks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ขนมปังชีสโรล.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ขนมปังหน้าหมูม้วนอัลมอนด์.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, 90));

        jLabel7.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("59 ฿");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 40, 50));

        jLabel8.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ขนมปังโรลชีส");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, 40));

        jLabel9.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("19 ฿");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, 50));

        jLabel10.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ขนมปังเสียบไม้");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, 80));

        jLabel12.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("89 ฿");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, 80));

        jLabel13.setFont(new java.awt.Font("TH Kodchasal", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ขนมปังม้วนอัลมอนด์");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 90));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\มันฝรั่งชุบเกล็คขนมปังทอด.jpg")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 140, 70));

        jLabel16.setFont(new java.awt.Font("TH Kodchasal", 1, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ขนมปัังอบชีส");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, 80));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ขนมปังอบชีส.jpg")); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 140));

        jLabel19.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("79 ฿");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 306, -1, 80));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ชีสทอดกรอบ.jpg")); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 130, 80));

        jLabel21.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("129 ฿");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, 40));

        jLabel22.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("พิซซ่าโรลแฮมชีส");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, 100));

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\พิซซ่าโรลแฮมชีส.jpg")); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, 90));

        jLabel24.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("อกไก่ชีสบอล");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, 30));

        jLabel25.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("109 ฿");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, -1, 40));

        jLabel27.setFont(new java.awt.Font("TH Kodchasal", 1, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("มันฝรั่งชุบแป้งทอด");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, 40));

        jLabel28.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("39 ฿");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, -1, 40));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ปอเปี๊ยะกุ้งชีส.jpg")); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 130, 80));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ขนมปังสังขยาโทสต์.jpg")); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 120, 70));

        jLabel11.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ขนมปังปิ้ง สังขยา");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, 80));

        jLabel29.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("29 ฿");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 80));

        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\ขนมปังเสียบไม้.jpg")); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, 90));

        jLabel33.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("ชีสทอดกรอบ");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, -1, 80));

        jLabel34.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("49 ฿");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 306, -1, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\อกไก่ชีสบอล.jpg")); // NOI18N
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 130, 80));

        jLabel36.setFont(new java.awt.Font("TH Kodchasal", 1, 23)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("ปอเปี๊ยะกุ้งชีส");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, 60));

        jLabel37.setFont(new java.awt.Font("TH Kodchasal", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("79 ฿");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, -1, 40));

        jButton1.setFont(new java.awt.Font("TH Baijam", 1, 14)); // NOI18N
        jButton1.setText("กลับ");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 500, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Windows10\\Desktop\\Projext\\photo-1578474846511-04ba529f0b88.jfif.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Project3 pj3 = new Project3();
        dispose();
        pj3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
